#!/usr/bin/env perl
use strict;
use warnings;

for my $csvfile (@ARGV) {
    my $jsonfile = $csvfile;
    $jsonfile =~ s,/,PATHSEP,g;
    $jsonfile =~ s/\W/-/g;
    $jsonfile =~ s/-csv$/.json/;
    $jsonfile =~ s,PATHSEP,/,g;
    print "Converting $csvfile -> $jsonfile\n";
    system("csv2json '$csvfile' > $jsonfile")
        and die "Failed to convert $csvfile: $!";
}
