#!/usr/bin/env perl
use strict;
use warnings;
use Email::Stuffer;

die "must set MAILTO" unless $ENV{MAILTO};
die "must set EMAIL"  unless $ENV{EMAIL};

my $buf        = '';
my $first_line = '';
while (<>) {
    $buf .= $_;
    chomp( $first_line ||= $_ );
}

$first_line =~ s/<.+?>//g;

Email::Stuffer->to( $ENV{MAILTO} )->from( $ENV{EMAIL} )
    ->subject( $ENV{SUBJECT} || $first_line )->html_body($buf)->send;

