#!/usr/bin/env perl
use strict;
use warnings;

# pull out header, then whatever is on stdin

my $usage    = "$0 file.csv < lines-of-csv\n";
my $csv_file = shift(@ARGV) or die $usage;
my $fh;
if ( $csv_file =~ m/\.gz$/ ) {
    open $fh, "-|", "gzcat $csv_file";
}
else {
    open $fh, "<", $csv_file;
}
my $header = <$fh>;
print $header;
print while (<>);
