#!/usr/bin/env perl
use strict;
use warnings;

my $usage = "$0 file.geojson fieldA fieldB .. fieldN";
my $file = shift(@ARGV) or die $usage;
my @fields;
for my $f (@ARGV) {
    push @fields, "\\(.$f)";
}
my $field_str = join( ',', @fields );

my @buf = `jq '.features[].properties | "$field_str"' < $file`;
for my $ln (@buf) {
    $ln =~ s/^"|"$//g;
    print $ln;
}
