#!/bin/sh

CURRENT_BRANCH=`git branch | grep \* | cut -d ' ' -f2`
git fresh
if [ "$CURRENT_BRANCH" == "master" ]; then
  echo "Already updated on master"
fi
git checkout $CURRENT_BRANCH
git rebase master
