#!/bin/sh

CURRENT_BRANCH=`git branch | grep \* | cut -d ' ' -f2`
MAIN_BRANCH=`git remote show origin | grep 'HEAD branch' | sed 's/.*: //'`
git fresh
if [ "$CURRENT_BRANCH" == "master" ]; then
  echo "Already updated on master"
fi
git checkout $CURRENT_BRANCH
git rebase $MAIN_BRANCH
