#!/bin/sh

# pull latest master, rebase with upstream
if [ -d .git ]; then
  git checkout master
  git pull --rebase
  git fetch upstream
  git rebase upstream/master
else
  echo "Not a git repository."
fi
