#!/bin/bash

if [[ $# -lt 2 ]]; then
  echo "git setup url email"
  exit
fi

url=$1
email=$2
reponame=`echo $url | perl -n -e 's,.+/|\.git$,,g; print'`

git clone $url
cd $reponame
git config user.email $email
echo '. ~/my-toolbox/git-protect-main-branch' >> .git/hooks/pre-commit
chmod 755 .git/hooks/pre-commit
