#!/bin/sh

# pull latest master, clean up old branches
if [ -d .git ]; then
  git checkout `git remote show origin | grep 'HEAD branch' | sed 's/.*: //'` 
  git pull
  git remote prune origin
  git branch -vv | grep ': gone]' | awk '{print $1}' | xargs git branch -D
else
  echo "Not a git repository or you need to chdir to top level."
fi
