#!/usr/bin/env perl

use strict;
use warnings;

unless ( $^O =~ m/darwin/i ) {
    exec "/usr/bin/md5sum", @ARGV;
}

if (-e "/usr/local/bin/md5sum") {
    exec "/usr/local/bin/md5sum", @ARGV;
}

for my $md5file (@ARGV) {
    next if $md5file =~ m/^-/;
    unless (-r $md5file) {
        warn "No such file $md5file";
        next;
    }
    my ($orig) = ( $md5file =~ m/(.+)\.md5$/ );
    unless (-r $orig) {
        warn "No signature file $orig";
        next;
    }
    chomp( my $md5   = `md5 -r $orig` );
    chomp( my $check = `cat $md5file` );
    $md5 =~ s/\s+.+//g;
    $check =~ s/\s+.+//g;
    if ( $md5 eq $check ) {
        print "signatures match: $md5\n$orig: OK\n";
    }
    else {
        print "signatures do not match:\n";
        print "MD5: $md5\n";
        print "SIG: $check\n";
    }
}
