#!/usr/bin/env perl
use strict;
use warnings;
use Carp;

printf("%s\n", random_str(@ARGV));

sub random_str {
    my $n = shift || 16;
    my $specials = shift || 0;
    if ( $n =~ m/\D/ ) {
        croak "error: 'n' must be a positive integer, not $n";
    }
    my @chars = ( "A" .. "N", "P" .. "Z", "a" .. "k", "m" .. "z", 0 .. 9, );
    push @chars, '!', '?', '%', '$', '.', '@' if $specials;
    return join( "", @chars[ map { rand @chars } ( 1 .. $n ) ] );
}

