#!/usr/bin/env perl

use strict;
use warnings;
my $arg = join(' ', map { m/\s/ ? qq/'$_'/ : $_ } @ARGV);
my $cmd = "grep -r --exclude=.phptidybak $arg | grep -v .svn | grep -v .git"; 
warn $cmd , $/;
system("$cmd");

