#!/usr/bin/env perl

# ogr2ogr -f GeoJSON -t_srs crs:84 [name].geojson [name].shp

my $usage    = "$0 file.shp [s_srs]\n";
my $shp_file = shift(@ARGV) or die $usage;
my $s_srs    = shift(@ARGV) || 'crs:84';
( my $bare_file = $shp_file ) =~ s/\.shp$//;
my $geojson = "$bare_file.geojson";
die $usage if $bare_file eq $shp_file;

if ( -s $geojson ) {
    die "$geojson already exists\n";
}

my $cmd = "ogr2ogr -f GeoJSON -t_srs crs:84 -s_srs $s_srs $geojson $shp_file";
system($cmd) and die "$cmd failed: $!";
