#!/bin/bash

# set -x
set -e

NOW=`date '+%Y%m%d-%H%M%S'`
SUBDIR=`date '+%Y%m%d'`
mkdir -p $HOME/solar/$SUBDIR
HOST=172.27.153.1
#HOST=www.sunpowerconsole.com
URL="http://$HOST/cgi-bin/dl_cgi?Command=DeviceList"
FILE="$HOME/solar/$SUBDIR/$NOW.json"

curl -s $URL > $FILE

myfilesize=$(stat --format=%s $FILE)
[ -s $FILE ] || echo "$FILE is empty"
if [ "$myfilesize" == "0" ]
then
  echo "empty curl response"
  exit 1
fi

$HOME/perlbin/perl $HOME/bin/solar-index $FILE
