#!/usr/bin/env perl
use strict;
use warnings;

use File::Slurper qw( read_binary );
use Search::Tools::UTF8 qw( is_sane_utf8 is_valid_utf8 find_bad_utf8 );

while (<ARGV>) {
    my $buf = $_; #read_binary($f);
    if ( !is_valid_utf8($buf) ) {
        is_sane_utf8($buf, 1);
        warn substr(find_bad_utf8($buf), 0, 100);
    }
}
