#!/usr/bin/env perl

use strict;
use warnings;

for my $xfile (@ARGV) {
    my $csvfile = $xfile;
    if ( $xfile =~ /\.xls$/i ) {
        system("xls2csv-separate-sheets.pl --infile '$xfile'")
            and die "failed to convert $xfile: $!";
    }
    elsif ( $xfile =~ /\.xlsx$/i ) {
        $csvfile =~ s/\W/-/g;
        $csvfile =~ s/-xlsx$/.csv/i;
        print "Processing $xfile -> $csvfile...\n";
        system("xlsx2csv '$xfile' > $csvfile")
            and die "failed to convert $xfile: $!";
    }
}
